require: rubocop-rails

Layout/LineLength:
  Enabled: true
  Max: 85

Style/Documentation:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Rails/EnumHash:
  Enabled: false

Naming/FileName:
  Enabled: true
  Exclude:
    - "config/initializers/rswag-ui.rb"

Layout/ExtraSpacing:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "spec/controllers/concerns/tickets/filters_spec.rb"
    - "spec/controllers/v1/tickets_controller_spec.rb"
    - "spec/integration/tickets_spec.rb"
    - "spec/models/concerns/plate_validator_spec.rb"
    - "spec/models/concerns/reservation_spec.rb"
    - "spec/models/ticket_spec.rb"

Style/Semicolon:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - "spec/controllers/concerns/tickets/filters_spec.rb"
    - "spec/factories/ticket.rb"
